### ISSUE TITLE
Running `run_simulation.py` with calibrate_model=True raises an Exception

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/OG-USA#118]
If you change line 50 of `run_simulation.py` to:

```
calibrate_model = True
```

You will get this exception:

```
Traceback (most recent call last):
  File "run_simulation.py", line 81, in <module>
    ss_outputs = SS.run_steady_state(ss_parameters, iterative_params, get_baseline, calibrate_model)
  File "/Users/talumbau/dev/ospc-dynamic/dynamic/Python/dynamic/SS.py", line 408, in run_steady_state
    chi_params_scalars = opt.minimize(function_to_minimize_X, chi_params_scalars, method='TNC', tol=MINIMIZER_TOL, bounds=bnds, options=MINIMIZER_OPTIONS).x
  File "/Users/talumbau/miniconda3/envs/ospcdyn/lib/python2.7/site-packages/scipy/optimize/_minimize.py", line 430, in minimize
    **options)
  File "/Users/talumbau/miniconda3/envs/ospcdyn/lib/python2.7/site-packages/scipy/optimize/tnc.py", line 398, in _minimize_tnc
    xtol, pgtol, rescale, callback)
  File "/Users/talumbau/miniconda3/envs/ospcdyn/lib/python2.7/site-packages/scipy/optimize/tnc.py", line 355, in func_and_grad
    f = fun(x, *args)
  File "/Users/talumbau/dev/ospc-dynamic/dynamic/Python/dynamic/SS.py", line 401, in <lambda>
    function_to_minimize_X = lambda x: function_to_minimize(x, chi_params, ss_parameters, iterative_params, omega_SS, rho, lambdas, tau_bq, e, output_dir)
  File "/Users/talumbau/dev/ospc-dynamic/dynamic/Python/dynamic/SS.py", line 322, in function_to_minimize
    solutions = SS_solver(b_guess.reshape(S, J), n_guess.reshape(S, J), wguess,
TypeError: check_wealth_calibration() takes exactly 4 arguments (3 given)

```

I'm not sure if this was caused by the refactoring activity, but essentially the issue is that we have not tested the code paths resulting from executing with this flag set to `True`. Someone should take on the challenge of running this script from start to finish with this flag set to true. This is more to make sure all of the code triggered by this flag runs, since I'm uncertain how to test the results of running in such a way.

**Comment by jdebacker** [comment]
We are no longer running calibration in this way.
